sval='1234'
type(sval)
print(type(sval))
print(sval)
tval=int(sval)
type(tval)
print(type(tval))
print(tval+2)
abc="12"
xyz="88"
print(type(abc))
print(type(xyz))
print ("abc=" , abc)
print("xyz=" ,xyz)
print("abc+xyz=" , abc+xyz)
print("abc+xyz=" , abc + xyz)
n=int(abc)
m=float(xyz)
print ("n=" , n)
print ("m=" , m)
print("n+m=" , n+m)
done="string conversion concept is clear"
print(done)
name= input("who are you")
print("Welcome",name)
tell= input("are you enjoying learning python language")
print( name , 'your answer is' ,tell)
print("User input concept simple exercise is done")